<?php

namespace frontend\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\BaseActiveRecord;
use yii\web\UploadedFile;

/**
 * This is the model class for table "files".
 *
 * @property int $id
 * @property string $title
 * @property string $type
 * @property string $path
 * @property int $user_id
 * @property string $created_at
 * @property string|null $updated_at
 */
class File extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'files';
    }

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    BaseActiveRecord::EVENT_BEFORE_INSERT => ['created_at'],
                    BaseActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => function(){
                    return gmdate("Y-m-d H:i:s");
                },
            ],
        ];
    }

    /**
     * @return bool
     * @throws \Exception
     */
    public function beforeDelete()
    {
        if (file_exists($this->path) && !unlink($this->path)) {
            throw new \Exception('Can not delete file');
        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'type', 'path', 'user_id'], 'required'],
            [['user_id'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['title', 'type', 'path'], 'string', 'max' => 255],
            ['type', 'validateType'],
        ];
    }

    public function validateType($attribute)
    {
        if (!in_array($this->$attribute, Yii::$app->params['allowed_files'])) {
            $this->addError($attribute, 'Файлы должены иметь расширения: ' . join(', ', Yii::$app->params['allowed_files']));
        }
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'type' => 'Type',
            'path' => 'Path',
            'user_id' => 'User ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public static function uploadAttaches(array $attaches, string $dir = null): array
    {
        $files = [];
        foreach ($attaches as $attach) {
            if ($file = (new static())->upload($attach, $dir)) {
                $files[] = $file;
            }
        }

        return $files;
    }

    /**
     * @param UploadedFile $attach
     * @param string|null $dir
     * @return File|null
     * @throws \Exception
     */
    public function upload(UploadedFile $attach, string $dir = null): ?self
    {
        $path = $dir ?? Yii::$app->params['storage_uploads'];

        if (!is_dir($path) && !mkdir($path)) {
            throw new \Exception('Can not create path');
        }

        $this->title = $attach->baseName;
        $this->type = $attach->extension;
        $this->path = $path . '/' . time() . '-' . $attach->name;
        $this->user_id = Yii::$app->user->getId();

        if (!in_array(explode('.', $attach->name)[1], Yii::$app->params['allowed_files'])) {
            return null;
        }

        if ($this->validate() && $this->save()) {
            $attach->saveAs($this->path);

            return $this;
        }

        return null;
    }

    /**
     * @return string
     */
    public function getUrl(): string
    {
        if (strpos($this->path, '/uploads') !== false) {
            return substr($this->path, strpos($this->path, '/uploads'));
        }

        return '#';
    }
}
